Repository af83/chouette-core, pull requests merged in 2018-11, with the labels that each got.

#991 Fix multiple mail sending and wrong status in mail Refs #9028
  app/mailers/export_mailer.rb
  app/mailers/import_mailer.rb
  app/models/export_observer.rb
  app/models/import_observer.rb
  app/views/export_mailer/finished.html.slim
  app/views/import_mailer/finished.html.slim
  spec/models/export/export_observer_spec.rb
  spec/models/import/import_observer_spec.rb
Labels: bug, urgent

#994 9081; Fix font in mails
  app/assets/stylesheets/mailers/components/h2.sass
  app/assets/stylesheets/mailers/components/h3.sass
  app/assets/stylesheets/mailers/components/mail_header.sass
  app/assets/stylesheets/mailers/components/tbody.sass
  app/assets/stylesheets/mailers/components/th.sass
  config/environments/production.rb.sample
Labels: bug, urgent

#999 8612 Don't show link to import
  app/policies/import_policy.rb
  app/views/referentials/show.html.slim
  spec/policies/import_policy_spec.rb
Labels: bug, small

#1009 9147 Updates VJs checksums when a stop_point position changes
  app/models/chouette/vehicle_journey.rb
  spec/models/chouette/vehicle_journey_spec.rb
Labels: bug, urgent

#1005 9141 Make aggregated referentials exportables
  app/controllers/exports_controller.rb
  app/views/exports/_form.html.slim
Labels: enhancement, small

#973 8941 Optimize ReferentialVehicleJourneysController#index
  .gitignore
  app/controllers/referential_vehicle_journeys_controller.rb
  app/models/chouette/time_table.rb
  app/models/chouette/vehicle_journey.rb
  app/services/referential_consolidated.rb
  app/views/referential_vehicle_journeys/_consolidated.html.slim
  app/views/referential_vehicle_journeys/_consolidated_line.html.slim
  spec/models/chouette/vehicle_journey_spec.rb
  spec/models/export/gtfs_spec.rb
Labels: bug

#1006 Refs #8873 In the timetable period form, set year options depending on the modalProps begin year and last year.
  app/javascript/time_tables/components/PeriodForm.js
Labels: small

#1007 Refs #9119 Change wording on aggregates#show
  app/views/aggregates/show.html.slim
  config/locales/aggregates.en.yml
  config/locales/aggregates.fr.yml
Labels: small

#998 8482 Fix titles with very long word
  app/assets/javascripts/ellipsis.coffee
Labels: enhancement, small

#1024 Refs #8909 add street name to stop areas show view
  app/views/stop_areas/show.html.slim
Labels: enhancement, small

#938 Refs #8273 Add Empty timetable compliance control
  app/models/chouette/time_table.rb
  app/models/compliance_control.rb
  app/models/vehicle_journey_control/empty_time_table.rb
  config/locales/compliance_controls.en.yml
  config/locales/compliance_controls.fr.yml
  spec/factories/chouette_time_table.rb
  spec/models/compliance_controls/vehicle_journey_control/empty_time_table_spec.rb
Labels: enhancement

#978 Refs #8894 Rename workbenches#edit & workbenches#update routes
  app/assets/stylesheets/components/_main_nav.sass
  app/controllers/workbenches_controller.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/workbenches/_form.html.slim
  app/views/workbenches/edit_controls.html.slim
  app/views/workbenches/show.html.slim
  config/breadcrumbs.rb
  config/locales/layouts.en.yml
  config/locales/layouts.fr.yml
  config/locales/stop_area_providers.en.yml
  config/locales/workbenches.en.yml
  config/locales/workbenches.fr.yml
  config/routes.rb
  spec/views/layouts/menu.html.erb_spec.rb
Labels: small, urgent
