Repository af83/chouette-core, pull requests merged in 2018-09, with the labels that each got.

#871 7860 Fix VJs times computation
  app/javascript/vehicle_journeys/reducers/vehicleJourneys.js
  spec/javascript/vehicle_journeys/actions_spec.js
  spec/javascript/vehicle_journeys/reducers/vehicleJourneys_spec.js
Labels: bug

#870 7044 Show referential name in exports
  app/controllers/concerns/iev_interfaces.rb
  app/views/exports/index.html.slim
  app/views/exports/show.html.slim
  app/views/shared/iev_interfaces/_filters.html.slim
  config/locales/exports.fr.yml
Labels: enhancement, small

#881 Refs #8093 #merged? to Referential destroy policy
  app/policies/referential_policy.rb
  spec/policies/referential_policy_spec.rb
Labels: bug

#856 7502 Fix Calendar declaration
  app/models/calendar.rb
  app/models/calendar/date_value.rb
  app/models/calendar/period.rb
Labels: refactoring, small

#882 8006 Fix StopAreaProvider CRUD
  app/controllers/stop_area_providers_controller.rb
Labels: bug, small

#883 8011 + 8009 Fix ransack with objectid
  config/initializers/ransack_objectid.rb
Labels: bug, small

#885 7774 Hide operations panel
  app/views/layouts/navigation/_main_nav_top.html.slim
  app/views/layouts/navigation/_nav_panel_operations.html.slim
Labels: small

#886 8010 Clean project-specific initializer
  config/initializers/codifligne.rb
  config/locales/companies.fr.yml
  config/locales/networks.fr.yml
Labels: small

#896 Refs #8141 Fix imports#index by adding human_name method to Import:Ba…
  app/models/import/base.rb
Labels: bug, small, urgent

#888 remove url validation in companies. Refs #8132
  app/models/chouette/company.rb
Labels: bug

#899 Refs #8154 Require dummy control only in development
  app/models/compliance_control.rb
Labels: enhancement, urgent

#898 Refs #8152 Add validation for Merge referential presence
  app/models/merge.rb
  config/locales/merges.en.yml
  config/locales/merges.fr.yml
Labels: bug, urgent

#895 Authorize editing RoutingConstrainZone with minimum 2 StopPoint #7679 :
  app/models/chouette/route.rb
  app/models/chouette/routing_constraint_zone.rb
  app/views/routing_constraint_zones/new.html.slim
  config/locales/routing_constraint_zones.en.yml
  config/locales/routing_constraint_zones.fr.yml
Labels: bug, small

#877 Import route type. Refs #7971
  app/models/import/gtfs.rb
  spec/models/import/gtfs_spec.rb
Labels: bug

#875 8094 Keep delta in schedules when only departur time is shown
  app/javascript/vehicle_journeys/components/VehicleJourney.js
  app/javascript/vehicle_journeys/reducers/vehicleJourneys.js
Labels: enhancement

#889 Refs #7766 Fix extreme dates in GTFS imports
  app/models/import/base.rb
  app/models/import/gtfs.rb
  app/views/referentials/_period_fields.html.slim
  config/locales/imports.fr.yml
  spec/models/import/gtfs_spec.rb
Labels: bug

#884 6443 & 6444 Add missing icons for Exports
  app/assets/stylesheets/typography/_sboiv.sass
Labels: small

#872 8068 Fix Referential state during GTFS import
  app/models/import/gtfs.rb
Labels: bug

#893 8143 Invoke TomTom only after import is done
  app/models/chouette/route.rb
  app/models/import/gtfs.rb
  spec/models/import/gtfs_spec.rb
Labels: bug

#862 8020 Forbid empty Journey Patterns
  app/javascript/routes/form_helper.js
  app/models/chouette/journey_pattern.rb
  app/views/routes/_form.html.slim
Labels: bug

#901 8146 Remove deprecated field
  app/views/stop_areas/_form.html.slim
Labels: small

#829 7851 Remove project-dependant permissions translator
  app/models/permission.rb
  app/models/subscription.rb
  db/seeds/helpers/permissions.rb
  lib/stif/permission_translator.rb
  spec/lib/stif/permission_translator_spec.rb
Labels: enhancement

#878 Use objectid instead of id in gtfs export. Refs #7783
  app/models/export/gtfs.rb
  db/schema.rb
  spec/models/export/gtfs_spec.rb
Labels: bug

#852 7826 Fix vehicle journeys creation
  app/controllers/vehicle_journeys_controller.rb
  app/javascript/vehicle_journeys/reducers/modal.js
  app/javascript/vehicle_journeys/reducers/vehicleJourneys.js
  app/views/api/v1/journey_patterns/show.rabl
  spec/javascript/vehicle_journeys/actions_spec.js
  spec/javascript/vehicle_journeys/reducers/vehicleJourneys_spec.js
Labels: bug

#904 Error message for routing constraint zone check on imports
  config/locales/import_messages.en.yml
  config/locales/import_messages.fr.yml
Labels: bug

#897 8148 Log errors in gtfs imports
  Gemfile
  Gemfile.lock
  app/helpers/imports_helper.rb
  app/models/concerns/iev_interfaces/message.rb
  app/models/concerns/iev_interfaces/resource.rb
  app/models/import/base.rb
  app/models/import/gtfs.rb
  app/models/import/message_export.rb
  app/views/imports/import/_gtf.html.slim
  app/views/imports/import/_workbench.html.slim
  config/environments/test.rb
  config/locales/import_messages.en.yml
  config/locales/import_messages.fr.yml
  config/locales/imports.en.yml
  config/locales/imports.fr.yml
  spec/models/import/gtfs_spec.rb
Labels: enhancement

#892 8129 merge rollback
  app/controllers/merges_controller.rb
  app/decorators/merge_decorator.rb
  app/helpers/imports_helper.rb
  app/javascript/helpers/cancel_button.js
  app/javascript/vehicle_journeys/components/CancelVehicleJourneys.js
  app/models/merge.rb
  app/models/referential.rb
  app/policies/merge_policy.rb
  app/views/merges/show.html.slim
  config/locales/merges.en.yml
  config/locales/merges.fr.yml
  config/routes.rb
  db/schema.rb
  spec/decorators/merge_decorator_spec.rb
  spec/factories/merges.rb
  spec/models/merge_spec.rb
  spec/models/referential_spec.rb
  spec/policies/merge_policy_spec.rb
  spec/support/decorator_helpers.rb
Labels: enhancement

#922 8314 - Doesn't unarchived Merge referential when it's not valid
  app/models/merge.rb
  app/models/referential.rb
  spec/models/merge_spec.rb
Labels: bug, urgent

#923 8255 Fix Imports migration
  db/migrate/20180905131655_add_options_to_imports.rb
Labels: bug, urgent

#918 8254 Add specs
  app/models/chouette/journey_pattern.rb
  spec/models/chouette/journey_pattern_spec.rb
Labels: enhancement

#915 8218 Fix Sticky header css
  app/assets/javascripts/main_menu.coffee
  app/assets/stylesheets/components/_main_nav.sass
Labels: bug, small

#909 Display Workbench Id with api keys. Refs #8161
  app/views/api_keys/index.html.slim
  config/locales/api_keys.en.yml
  config/locales/api_keys.fr.yml
Labels: small

#879 8022 env wrapper
  app/models/chouette/route.rb
  app/models/simple_importer.rb
  config/application.rb
  config/database.yml
  config/database.yml.docker
  config/database/ci.yml
  config/environments/development.rb
  config/environments/production.rb.sample
  config/environments/test.rb
  config/initializers/0_before_initialization.rb
  config/initializers/apartment_null_db.rb
  config/initializers/sidekiq.rb
  config/initializers/workbench_import.rb
  config/initializers/zzz_chouette_env.rb
  config/routes.rb
  db/seeds/helpers/workgroups.rb
  lib/ievkit/client.rb
  lib/ievkit/default.rb
  lib/smart_env.rb
  spec/lib/chouette_env_spec.rb
Labels: enhancement

#914 Merge#prepare_new now creates a Referential with ready: false. Refs #…
  app/models/merge.rb
  spec/models/merge_spec.rb
Labels: bug

#874 8061 Ensure we protect data from other organizations
  app/controllers/autocomplete_time_tables_controller.rb
  app/controllers/calendars_controller.rb
  app/controllers/chouette_controller.rb
  app/controllers/companies_controller.rb
  app/controllers/compliance_controls_controller.rb
  app/controllers/group_of_lines_controller.rb
  app/controllers/import_messages_controller.rb
  app/controllers/import_resources_controller.rb
  app/controllers/line_referentials_controller.rb
  app/controllers/lines_controller.rb
  app/controllers/merges_controller.rb
  app/controllers/networks_controller.rb
  app/controllers/referential_lines_controller.rb
  app/controllers/referential_vehicle_journeys_controller.rb
  app/controllers/referentials_controller.rb
  app/controllers/stop_area_referentials_controller.rb
  app/controllers/stop_areas_controller.rb
  app/controllers/workgroups_controller.rb
  app/models/organisation.rb
  config/routes.rb
  spec/controllers/api_keys_controller_spec.rb
  spec/controllers/calendars_controller_spec.rb
  spec/controllers/compliance_check_sets_controller_spec.rb
  spec/controllers/compliance_control_blocks_controller_spec.rb
  spec/controllers/exports_controller_spec.rb
  spec/controllers/footnotes_controller_spec.rb
  spec/controllers/import_messages_controller_spec.rb
  spec/controllers/import_resources_controller_spec.rb
  spec/controllers/imports_controller_spec.rb
  spec/controllers/line_referentials_controller_spec.rb
  spec/controllers/merges_controller_spec.rb
  spec/controllers/referential_lines_controller_spec.rb
  spec/controllers/referentials_controller_spec.rb
  spec/controllers/routes_controller_spec.rb
  spec/controllers/stop_area_referentials_controller_spec.rb
  spec/controllers/workbench_outputs_controller_spec.rb
  spec/controllers/workgroups_controller_spec.rb
  spec/features/compliance_check_sets_spec.rb
  spec/support/shared_examples/current_organisation.rb
Labels: bug

#934 Refs #8237 Fix color display of PW on consolidated offer view
  app/views/referential_vehicle_journeys/_consolidated_line.html.slim
Labels: small

#916 Fix i18n for compliance check sets steps Refs #8245 @1
  app/models/workgroup.rb
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
Labels: small

#910 8221 - Add rake task cucumber:clean_test_organisations
  config/schedule.rb
  lib/tasks/cucumber.rake
Labels: enhancement

#906 8204 - Add first transactions in Merge operation
  app/models/merge.rb
Labels: enhancement

#887 Refs #7784 Add validation to prevent stop area with parent to have a …
  app/models/chouette/stop_area.rb
  config/locales/stop_areas.en.yml
  config/locales/stop_areas.fr.yml
  spec/models/chouette/stop_area_spec.rb
Labels: small
