Repository af83/chouette-core, pull requests merged in 2018-12, with the labels that each got.

#1032 9295 Fix Aggregation result show
  app/services/referential_overview.rb
Labels: urgent

#1036 9303 Add missing i18n
  app/models/compliance_control.rb
  config/locales/compliance_controls.en.yml
  config/locales/compliance_controls.fr.yml
Labels: bug, small

#1042 Refs #9127 Fix spelling for holes notification email
  config/locales/mailers.fr.yml
Labels: small, urgent

#1013 Refs #9004 Clean previous aggregates on success
  app/models/aggregate.rb
  spec/models/aggregate_spec.rb
Labels: enhancement, urgent

#1004 Refs #9012 Fix time table updated at sort
  app/controllers/time_tables_controller.rb
Labels: small, urgent

#1002 9124 Fix consolidated offer JS
  app/javascript/referential_overview/index.coffee
Labels: enhancement, urgent

#1039 9329 Fix aggregation bug
  app/services/referential_copy.rb
Labels: urgent

#1014 Refs #9088 Purge exports
  app/models/concerns/purgeable_resource.rb
  app/models/export/base.rb
  app/models/import/base.rb
  app/models/import/gtfs.rb
  app/models/import/netex.rb
  spec/models/export/base_spec.rb
  spec/models/import/base_spec.rb
Labels: enhancement, urgent

#1022 Refs #9218 Reorganize menu-items
  app/assets/stylesheets/components/_main_nav.sass
  app/assets/stylesheets/partials/header.sass
  app/views/layouts/navigation/_main_nav_top.html.slim
Labels: bug, refactoring, small

#1029 9278 Fix Audit cron syntax
  app/mailers/audit_mailer.rb
  config/initializers/cron.rb
  lib/cron.rb
Labels: bug, small

#1059 9579 Fix workgroups permissions
  app/policies/workgroup_policy.rb
  spec/policies/workgroup_policy_spec.rb
  spec/views/layouts/menu.html.erb_spec.rb
Labels: bug, small

#1030 Refs #8446 fix referential slug format
  app/models/referential.rb
  spec/models/referential_spec.rb
Labels: bug, small

#1075 9656 fix gtfs import
  app/models/import/gtfs.rb
  config/locales/import_messages.en.yml
  config/locales/import_messages.fr.yml
  spec/fixtures/invalid_stop_times.zip
  spec/models/import/gtfs_spec.rb
Labels: bug, urgent

#960 8673 Checksum Manager
  app/models/chouette/vehicle_journey_at_stops_day_offset.rb
  app/models/concerns/checksum_support.rb
  app/models/custom_field.rb
  app/models/merge.rb
  config/environments/development.rb
  config/environments/test.rb
  lib/chouette/checksum_manager.rb
  lib/chouette/checksum_manager/base.rb
  lib/chouette/checksum_manager/inline.rb
  lib/chouette/checksum_manager/serialized_object.rb
  lib/chouette/checksum_manager/transactional.rb
  spec/lib/chouette/checksum_manager/inline_spec.rb
  spec/lib/chouette/checksum_manager/transactional_spec.rb
  spec/lib/chouette/checksum_manager_spec.rb
  spec/models/chouette/time_table_spec.rb
  spec/models/chouette/vehicle_journey_spec.rb
  spec/support/helpers/checksum_helpers.rb
Labels: enhancement

#1023 Refs #8987 better confirm action text
  app/javascript/helpers/cancel_button.js
  config/locales/en.yml
  config/locales/fr.yml
Labels: dontmerge, enhancement, small

#1062 Refs #9549 Add merge actions links
  app/controllers/workbench_outputs_controller.rb
  app/decorators/merge_decorator.rb
  app/views/workbench_outputs/show.html.slim
  config/locales/merges.en.yml
  config/locales/merges.fr.yml
Labels: enhancement, small

#1085 9689 Fix ChecksumManager
  lib/chouette/checksum_manager.rb
  spec/models/chouette/vehicle_journey_spec.rb
Labels: bug, small, urgent

#1038 9120 bulletproof notifiers
  app/models/aggregate_observer.rb
  app/models/compliance_check_set_observer.rb
  app/models/export_observer.rb
  app/models/import_observer.rb
  app/models/merge_observer.rb
  app/observers/aggregate_observer.rb
  app/observers/calendar_observer.rb
  app/observers/compliance_check_set_observer.rb
  app/observers/export_observer.rb
  app/observers/import_observer.rb
  app/observers/merge_observer.rb
  app/observers/notifiable_operation_observer.rb
  app/observers/route_observer.rb
  spec/models/compliance_check_set_observer_spec.rb
Labels: enhancement

#1088 Refs #9491 Rename left menu workgroup subtitle
  config/locales/layouts.en.yml
  config/locales/layouts.fr.yml
Labels: small

#1056 Refs #9547 Show icon of current output merge
  app/helpers/merges_helper.rb
  app/models/merge.rb
  app/views/workbench_outputs/show.html.slim
  config/locales/merges.en.yml
  config/locales/merges.fr.yml
Labels: enhancement, small

#1072 9625 Remove erroneous log on Workbenches
  app/models/workbench.rb
Labels: bug, small

#1097 7734 referential unarchive
  app/controllers/referentials_controller.rb
Labels: small

#1098 9737 main nav left exports
  app/views/layouts/navigation/_main_nav_left_content.html.slim
Labels: enhancement, small

#1094 Refs #9739 Add a translation to 'blank option' in workbench edit cont…
  app/views/workbenches/_form.html.slim
  config/locales/workbenches.en.yml
  config/locales/workbenches.fr.yml
Labels: enhancement, small

#1035 8154 Disable DummyCOntrol in production
  app/models/compliance_control.rb
  app/models/dummy_control/dummy.rb
  app/models/internal_control/base.rb
  config/application.rb
  config/environments/development.rb
Labels: bug, small, urgent
