Repository af83/chouette-core, pull requests merged in 2018-06, with the labels that each got.

#606 Refs #7259 Add seasonal attribute to line form
  app/views/lines/_form.html.slim
Labels: small

#607 Refs #6955 Add some new translations
  app/decorators/compliance_control_decorator.rb
  app/decorators/compliance_control_set_decorator.rb
  app/decorators/purchase_window_decorator.rb
  app/decorators/referential_network_decorator.rb
  app/decorators/route_decorator.rb
  app/decorators/routing_constraint_zone_decorator.rb
  app/decorators/stop_area_decorator.rb
  app/views/line_footnotes/_footnote_fields.html.slim
  config/locales/compliance_control_sets.en.yml
  config/locales/footnotes.en.yml
  config/locales/footnotes.fr.yml
Labels: small

#609 Refs #6838 Add presence validation on periods for purchase windows
  app/models/chouette/purchase_window.rb
  spec/models/chouette/purchase_window_spec.rb
Labels: small

#560 Refs #6668 add begin_of_association_chain for merges controller
  app/controllers/merges_controller.rb
Labels: small

#610 Refs #6629 Add Workbench & Workgroup to permission translator
  app/policies/workgroup_policy.rb
  app/views/workbenches/show.html.slim
  lib/stif/permission_translator.rb
  spec/support/permissions.rb
Labels: small

#625 7307 Permit deletion of failed and archived referentials
  app/policies/referential_policy.rb
  spec/decorators/referential_decorator_spec.rb
  spec/policies/referential_policy_spec.rb
Labels: bug

#641 7368 - Set allow_unconfirmed_access_for = 1.day when Subscription.enabled?
  app/controllers/subscriptions_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/subscription.rb
  app/models/user.rb
  app/views/devise/_links.html.slim
  app/views/devise/shared/_form_registration.html.slim
Labels: small

#637 Refs #6956 Fix validation error on form submit
  app/inputs/color_select_input.rb
Labels: small

#644 Refs #7273 Add some new translations
  app/assets/javascripts/select2.coffee
  app/decorators/referential_line_decorator.rb
  app/views/lines/_form.html.slim
  app/views/routing_constraint_zones/new.html.slim
  app/views/time_tables/_filter.html.slim
  app/views/time_tables/_form.html.slim
  app/views/time_tables/index.html.slim
  app/views/workbenches/show.html.slim
  config/breadcrumbs.rb
  config/locales/compliance_control_blocks.en.yml
  config/locales/compliance_control_blocks.fr.yml
  config/locales/lines.en.yml
  config/locales/merges.en.yml
  config/locales/routes.en.yml
  config/locales/routing_constraint_zones.en.yml
  config/locales/routing_constraint_zones.fr.yml
  config/locales/time_tables.en.yml
  config/locales/time_tables.fr.yml
Labels: small

#643 Refs #7381 Add event listeners to close the main_nav_left more easily
  app/assets/javascripts/main_menu.coffee
Labels: small

#629 7338 Migrate PurchaseWindow colors
  db/migrate/20180608082502_update_purchase_windows_colors.rb
Labels: small

#651 7402 Scope lines avalaible when creating a new Referential
  app/models/chouette/line.rb
  app/views/referentials/_form.html.slim
Labels: small

#653 Refs #6676 Change Purchase Window bounding dates format for vehicle j…
  app/views/vehicle_journeys/show.rabl
Labels: small

#660 Extend ActiveModel::Naming to include EnhancedModelI18n Refs #7451
  config/initializers/i18n.rb
Labels: bug

#662 Refs #7385 Sort sort companies and network by name in line form inputs
  app/views/lines/_form.html.slim
Labels: small

#666 Refs #7442 Display the right translation when VJ doesnt have TM or TSM
  app/javascript/vehicle_journeys/actions/index.js
Labels: small

#665 Refs #7384 Change Referential VJ Line filter to be case insensitive
  app/models/chouette/line.rb
Labels: small

#611 Refs #6865 Change Referential create button
  app/views/workbenches/show.html.slim
  spec/features/workbenches/workbenches_permissions_spec.rb
  spec/features/workbenches/workbenches_show_spec.rb
Labels: bug, small
