Repository af83/chouette-core, pull requests merged in 2018-10, with the labels that each got.

#912 Refs #8198 Fix Referential line select 2 search
  app/views/referentials/_form.html.slim
Labels: bug, small

#917 Refs #8157 Clean line & stop area referentials syncs to keep only 40
  app/controllers/line_referentials_controller.rb
  app/controllers/stop_area_referentials_controller.rb
  app/models/concerns/sync_support.rb
  app/models/line_referential.rb
  app/models/stop_area_referential.rb
  spec/models/line_referential_spec.rb
  spec/models/stop_area_referential_spec.rb
Labels: small

#808 7798 Trigger a cleanup when a Referential's lines are modified
  app/controllers/referentials_controller.rb
  app/models/clean_up.rb
  app/models/referential.rb
  app/workers/clean_up_worker.rb
  spec/factories/referentials.rb
  spec/models/clean_up_spec.rb
  spec/models/referential_spec.rb
Labels: dontmerge, enhancement

#905 8205 Add cache to ObjectId formatters
  app/models/chouette/objectid_formatter.rb
  app/models/chouette/trident_active_record.rb
  app/models/concerns/objectid_formatter_support.rb
  app/models/concerns/objectid_support.rb
  app/models/import/gtfs.rb
  lib/af83/smart_cache.rb
  spec/helpers/table_builder_helper_spec.rb
  spec/models/chouette/objectid_formatter_spec.rb
  spec/models/import/gtfs_spec.rb
Labels: enhancement

#908 8126 - Don't export non-commercial StopAreas
  app/models/export/gtfs.rb
  spec/models/export/gtfs_spec.rb
Labels: enhancement

#941 8491 - Add Organisation#api_keys through workbenches
  app/models/organisation.rb
  spec/models/organisation_spec.rb
Labels: small, urgent

#894 8142 Skip callbacks when updating metadatas
  app/models/concerns/metadata_support.rb
  spec/controllers/routes_controller_spec.rb
Labels: enhancement

#932 Refs #8313 Add specs on Stop area create for all kinds
  spec/factories/chouette_stop_areas.rb
  spec/models/chouette/stop_area_spec.rb
Labels: small

#931 8451 Add a optional locale in users seed
  db/seeds/helpers/workgroups.rb
Labels: dontmerge, enhancement

#944 Refs #8237 Fix pw color on consolidated view
  app/views/referential_vehicle_journeys/_consolidated_line.html.slim
Labels: small

#943 8425/6/7/8 aggregate operation
  app/assets/stylesheets/_misc.sass
  app/assets/stylesheets/components/_merges.sass
  app/controllers/aggregates_controller.rb
  app/controllers/compliance_check_sets_controller.rb
  app/controllers/compliance_checks_controller.rb
  app/controllers/workgroup_outputs_controller.rb
  app/controllers/workgroups_controller.rb
  app/decorators/aggregate_decorator.rb
  app/helpers/referentials_helper.rb
  app/models/aggregate.rb
  app/models/compliance_check_set.rb
  app/models/concerns/operation_support.rb
  app/models/merge.rb
  app/models/permission.rb
  app/models/referential.rb
  app/models/workbench.rb
  app/models/workgroup.rb
  app/policies/aggregate_policy.rb
  app/policies/workgroup_policy.rb
  app/views/aggregates/_form.html.slim
  app/views/aggregates/new.html.slim
  app/views/aggregates/show.html.slim
  app/views/compliance_check_sets/_filters.html.slim
  app/views/compliance_check_sets/executed.html.slim
  app/views/compliance_check_sets/show.html.slim
  app/views/compliance_checks/_filters.html.slim
  app/views/compliance_checks/show.html.slim
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/workgroup_outputs/show.html.slim
  app/views/workgroups/_form.html.slim
  app/workers/aggregate_worker.rb
  config/breadcrumbs.rb
  config/initializers/apartment.rb
  config/locales/aggregates.en.yml
  config/locales/aggregates.fr.yml
  config/locales/workgroup_outputs.en.yml
  config/locales/workgroup_outputs.fr.yml
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
  config/locales/zzz-stif.yml
  config/routes.rb
  db/migrate/20181003092810_create_aggregates.rb
  db/migrate/20181003101638_add_output_to_workgroups.rb
  db/migrate/20181003104628_add_creator_to_aggregates.rb
  db/migrate/20181003110259_add_started_and_ended_to_aggregates.rb
  db/migrate/20181003124924_add_compliance_control_set_ids_to_workgroups.rb
  db/schema.rb
  spec/controllers/workgroup_outputs_controller_spec.rb
  spec/factories/aggregates.rb
  spec/models/aggregate_spec.rb
  spec/models/merge_spec.rb
Labels: enhancement

#949 8506 Fix Timetables edit
  app/views/time_tables/show.rabl
Labels: enhancement, small

#951 8583 Copy referentials content in aggregation operations
  app/models/aggregate.rb
Labels: enhancement, urgent

#950 8577 Ignore empty values in custom fields checksums
  app/models/concerns/custom_fields_support.rb
  app/models/custom_field.rb
  spec/models/chouette/vehicle_journey_spec.rb
Labels: enhancement, urgent

#954 8541 Fix GTFS import
  app/models/import/gtfs.rb
  spec/fixtures/google-sample-feed.zip
  spec/models/import/gtfs_spec.rb
Labels: bug

#958 8506 Fix Timetable#show
  app/controllers/time_tables_controller.rb
Labels: enhancement, small

#959 8656 Fix css
  app/assets/stylesheets/_misc.sass
Labels: small, urgent

#962 Refs #8538; Try again TomTom computation
  app/models/chouette/route.rb
  app/workers/route_way_cost_worker.rb
  lib/tom_tom/delegator.rb
Labels: bug, urgent

#936 8482 Clean ellipsis on long titles
  app/assets/javascripts/application.js
  app/assets/javascripts/ellipsis.coffee
  app/assets/stylesheets/components/_main_nav.sass
  app/assets/stylesheets/components/_page_header.sass
Labels: enhancement

#913 8159 Add a permission to browse API keys
  app/controllers/api_keys_controller.rb
  app/models/permission.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  spec/controllers/api_keys_controller_spec.rb
  spec/features/api_keys/delete_api_key_feature_spec.rb
  spec/features/safe_submit_spec.rb
  spec/support/devise.rb
Labels: bug

#965 8837 Fix GTFS import when the source zip is missing a calendar_dates.txt file
  Gemfile.lock
  app/models/concerns/iev_interfaces/resource.rb
  app/models/import/gtfs.rb
  spec/fixtures/google-sample-feed-no-calendar_dates.zip
  spec/models/import/gtfs_spec.rb
Labels: bug, dontmerge, small

#967 8911 Prevent deletion of merged referentials
  app/controllers/workbenches_controller.rb
  app/views/workbenches/show.html.slim
  spec/controllers/workbenches_controller_spec.rb
  spec/views/offer_workbenches/show.html.erb_spec.rb
Labels: bug, urgent

#969 Refs 8919 Api imports index
  app/controllers/api/v1/imports_controller.rb
  app/views/api/v1/imports/show.rabl
Labels: small, urgent

#957 8611 Clean join tables during Route#clean!
  app/models/chouette/route.rb
  spec/models/clean_up_spec.rb
Labels: bug, small, urgent

#966 8858 Holes detection
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_misc.sass
  app/assets/stylesheets/components/_referential_overview.sass
  app/controllers/compliance_check_sets_controller.rb
  app/controllers/workgroups_controller.rb
  app/javascript/referential_overview/index.coffee
  app/mailers/sentinel_mailer.rb
  app/models/aggregate.rb
  app/models/chouette/journey_pattern.rb
  app/models/concerns/benchmark_support.rb
  app/models/merge.rb
  app/models/stat.rb
  app/models/stat/journey_pattern_courses_by_date.rb
  app/models/user.rb
  app/models/workbench.rb
  app/services/hole_sentinel.rb
  app/services/journey_pattern_offer_service.rb
  app/services/referential_copy.rb
  app/services/referential_overview.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/referentials/_overview.html.slim
  app/views/sentinel_mailer/notify_incoming_holes.html.slim
  app/views/workgroups/edit_hole_sentinel.html.slim
  config/breadcrumbs.rb
  config/locales/layouts.en.yml
  config/locales/layouts.fr.yml
  config/locales/mailers.en.yml
  config/locales/mailers.fr.yml
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
  config/routes.rb
  db/migrate/20181023084844_add_index_on_timetables_periods.rb
  db/migrate/20181023122025_create_stat_journey_pattern_courses_by_dates.rb
  db/migrate/20181025091329_add_sentinal_params_to_workgroups.rb
  db/schema.rb
  spec/factories/stat_journey_pattern_courses_by_dates.rb
  spec/models/stat/journey_pattern_courses_by_date_spec.rb
  spec/services/holes_sentinel_spec.rb
  spec/services/journey_pattern_offer_service_spec.rb
Labels: enhancement, urgent

#964 8551 Fix the times display
  app/helpers/vehicle_journeys_helper.rb
Labels: bug, urgent

#979 8968 Clean up new mails
  app/assets/stylesheets/mailers/components/content_table.sass
  app/assets/stylesheets/mailers/components/footer.sass
  app/assets/stylesheets/mailers/components/primary_table.sass
  app/mailers/sentinel_mailer.rb
  app/services/hole_sentinel.rb
  app/views/aggregate_mailer/finished.html.slim
  app/views/calendar_mailer/created.html.slim
  app/views/calendar_mailer/updated.html.slim
  app/views/calendars/_form_advanced.html.slim
  app/views/compliance_check_set_mailer/finished.html.slim
  app/views/devise/mailer/confirmation_instructions.html.slim
  app/views/devise/mailer/invitation_instructions.html.slim
  app/views/devise/mailer/reset_password_instructions.html.slim
  app/views/export_mailer/finished.html.slim
  app/views/import_mailer/finished.html.slim
  app/views/layouts/mailer.html.slim
  app/views/merge_mailer/finished.html.slim
  app/views/sentinel_mailer/notify_incoming_holes.html.slim
  app/views/subscription_mailer/created.html.slim
  app/views/user_mailer/created.html.slim
  config/locales/export_messages.en.yml
  config/locales/export_messages.fr.yml
  config/locales/mailers.en.yml
  config/locales/mailers.fr.yml
  spec/mailers/aggregate_mailer_spec.rb
  spec/mailers/calendar_mailer_spec.rb
  spec/mailers/compliance_check_set_mailer_spec.rb
  spec/mailers/export_mailer_spec.rb
  spec/mailers/import_mailer_spec.rb
  spec/mailers/merge_mailer_spec.rb
  spec/mailers/user_mailer_spec.rb
Labels: urgent
