Repository af83/chouette-core, pull requests merged in 2018-08, with the labels that each got.

#780 Refs #5986 reenable cache settings middleware
  config/environments/development.rb
  config/environments/production.rb
Labels: enhancement

#758 Refs #7254 Destroy unasscoaited footnotes after clean up
  app/models/chouette/footnote.rb
  app/models/clean_up.rb
  spec/models/clean_up_spec.rb
Labels: bug

#759 Refs #7508 Destroy unassociated timetables and purchase windows after…
  app/models/chouette/purchase_window.rb
  app/models/chouette/time_table.rb
  app/models/clean_up.rb
  app/models/merge.rb
  spec/models/clean_up_spec.rb
Labels: enhancement

#790 6622 Fix merge
  app/models/merge.rb
  spec/models/merge_spec.rb
Labels: bug

#781 #7408 source_label uninitialized in import messages
  config/locales/import_messages.en.yml
  config/locales/import_messages.fr.yml
Labels: bug

#772 Refs #7721 Import Chouette-its colors into chouette-core
  app/assets/stylesheets/OpenLayers/custom.sass
  app/assets/stylesheets/_layout.sass
  app/assets/stylesheets/base/_config.sass
  app/assets/stylesheets/components/_buttons.sass
  app/assets/stylesheets/components/_forms.sass
  app/assets/stylesheets/components/_main_nav.sass
  app/assets/stylesheets/components/_merges.sass
  app/assets/stylesheets/components/_modals.sass
  app/assets/stylesheets/components/_page_header.sass
  app/assets/stylesheets/components/_pagination.sass
  app/assets/stylesheets/components/_panels.sass
  app/assets/stylesheets/components/_referential_overview.sass
  app/assets/stylesheets/components/_select2.sass
  app/assets/stylesheets/components/_tables.sass
  app/assets/stylesheets/modules/_jp_collection.sass
  app/assets/stylesheets/modules/_routes_stopoints.sass
  app/assets/stylesheets/modules/_timetables.sass
  app/assets/stylesheets/modules/_vj_collection.sass
  app/assets/stylesheets/typography/_typography.sass
  app/views/errors/forbidden.html.slim
  app/views/errors/not_found.html.slim
  app/views/errors/server_error.html.slim
  app/views/layouts/navigation/_main_nav_top.html.slim
  config/locales/devise.en.yml
  config/locales/devise.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  spec/javascript/support/translations.js
Labels: refactoring

#770 7723 Clean seeds and seed_helpers
  db/seeds/dev/custom_fields.seeds.rb
  db/seeds/development/custom_fields.seeds.rb
  db/seeds/development/default.seeds.rb.sample
  db/seeds/helpers/active_record.rb
  db/seeds/helpers/permissions.rb
  db/seeds/helpers/workgroups.rb
  db/seeds/seed_helpers.rb
  db/seeds/stif.seeds.rb
Labels: refactoring

#800 7733 Make CAS behaviour customizable
  app/models/organisation.rb
  app/models/user.rb
  config/initializers/cron.rb
  lib/cron.rb
Labels: enhancement, refactoring, urgent

#785 7749 Make StopArea parent deletable
  app/views/stop_areas/_form.html.slim
Labels: enhancement, small

#746 Refs #7679 Add validation error message for RCZ minimum length
  app/models/chouette/routing_constraint_zone.rb
  config/locales/routing_constraint_zones.en.yml
  config/locales/routing_constraint_zones.fr.yml
Labels: small

#804 Refs #7796 display RCZ action depending on routing_constraint_zone_ex…
  app/javascript/vehicle_journeys/components/Tools.js
  app/models/feature.rb
Labels: small, urgent

#806 7811 Optimize export form
  app/assets/stylesheets/_misc.sass
  app/models/referential.rb
  app/views/exports/_form.html.slim
Labels: enhancement, small

#803 7807 Only count successful merges when cleaning previous ones
  app/models/merge.rb
  spec/models/merge_spec.rb
Labels: enhancement, urgent

#761 7712 Update source referentials state during merge
  app/models/merge.rb
  db/schema.rb
  spec/models/merge_spec.rb
Labels: bug, urgent

#805 7813 Fix Referentials uniqueness validation
  app/models/referential.rb
  app/models/referential_metadata.rb
  spec/models/referential_metadata_spec.rb
  spec/models/referential_spec.rb
Labels: bug, small, urgent

#768 7819 & 7649 & 7696 timetables issues in Merge
  app/models/chouette/time_table.rb
  app/models/chouette/time_table_period.rb
  app/models/merge.rb
  spec/models/chouette/time_table_spec.rb
  spec/models/merge_spec.rb
Labels: bug, urgent

#802 7809 Prevent creation of new output in merge
  app/models/merge.rb
  spec/models/merge_spec.rb
Labels: bug, small

#814 Refs #7773 Set Referential#ready to false during GTFS import
  app/models/import/gtfs.rb
Labels: bug, small

#815 Refs #7817 Fetch calendar within workgroup
  app/controllers/autocomplete_calendars_controller.rb
Labels: bug, small

#813 Refs #7821 Set checksum attributes for VJ & JP to disabled
  app/javascript/journey_patterns/components/EditModal.js
  app/javascript/vehicle_journeys/components/tools/EditVehicleJourney.js
Labels: small

#812 Refs #7679 Fix validation error message
  app/models/chouette/routing_constraint_zone.rb
Labels: bug, small

#754 Default pool_size set to 40
  config/database.yml.docker
Labels: enhancement, small

#797 Refs #7717 Benchmark gtfs import operations
  app/models/concerns/benchmark_support.rb
  app/models/import/gtfs.rb
Labels: small

#824 7838 Fix permissions translator
  lib/stif/permission_translator.rb
  spec/lib/stif/permission_translator_spec.rb
Labels: bug, small

#784 7739 Make sidekiq a tad more verbose
  config/initializers/sidekiq.rb
Labels: enhancement, small

#725 Use the audit to generate a report of every "useful" Referential
  app/mailers/audit_mailer.rb
  app/mailers/subscription_mailer.rb
  app/models/concerns/pretty_output.rb
  app/services/referential_audit/base.rb
  app/services/referential_audit/full.rb
  app/services/referential_audit/full_referential.rb
  app/services/referential_audit/journey_pattern_distances.rb
  app/services/referential_audit/purchase_windows_checksums.rb
  app/services/referential_audit/vehicle_journey_initial_offset.rb
  app/views/audit_mailer/audit.html.slim
  config/application.rb
  config/environments/development.rb
  config/initializers/cron.rb
  config/locales/mailers.en.yml
  config/locales/mailers.fr.yml
  lib/tasks/referential.rake
Labels: enhancement

#755 7538 Add a ransack scope to perform searches on short_id inste…
  app/controllers/autocomplete_lines_controller.rb
  app/models/chouette/objectid_formatter/base.rb
  app/models/chouette/objectid_formatter/netex.rb
  app/models/chouette/objectid_formatter/stif_codifligne.rb
  app/models/chouette/objectid_formatter/stif_netex.rb
  app/models/chouette/objectid_formatter/stif_reflex.rb
  app/models/chouette/trident_active_record.rb
  app/models/concerns/objectid_support.rb
  app/views/companies/index.html.slim
  app/views/lines/_filters.html.slim
  app/views/networks/index.html.slim
  app/views/referential_lines/_filters.html.slim
  app/views/referential_networks/index.html.slim
  app/views/referential_vehicle_journeys/_filters.html.slim
  app/views/referentials/_filters.html.slim
  app/views/referentials/_overview.html.slim
  app/views/routing_constraint_zones/_filters.html.slim
  app/views/shared/_lines_search_form.html.slim
  config/locales/companies.en.yml
  config/locales/companies.fr.yml
  config/locales/lines.en.yml
  config/locales/lines.fr.yml
  config/locales/networks.en.yml
  config/locales/networks.fr.yml
  config/locales/referentials.en.yml
  config/locales/referentials.fr.yml
  config/locales/routing_constraint_zones.en.yml
  config/locales/routing_constraint_zones.fr.yml
  spec/controllers/autocomplete_lines_controller_spec.rb
  spec/controllers/autocomplete_purchase_windows_controller_spec.rb
  spec/features/companies_spec.rb
  spec/features/lines_spec.rb
  spec/features/networks_spec.rb
  spec/models/chouette/vehicle_journey_spec.rb
Labels: enhancement

#825 7746 Update VJ checksum from React edition
  app/models/chouette/footnote.rb
  app/models/chouette/vehicle_journey.rb
Labels: bug, small

#821 6766 Allow negative offsets
  app/javascript/vehicle_journeys/components/tools/ShiftVehicleJourney.js
Labels: bug, small

#827 6869 Fix select width
  app/assets/stylesheets/_misc.sass
Labels: bug, small

#826 7730 Fix popup menu
  app/assets/javascripts/tables.coffee
  app/assets/stylesheets/components/_buttons.sass
  app/javascript/journey_patterns/components/JourneyPatterns.js
  app/javascript/vehicle_journeys/components/VehicleJourneys.js
Labels: bug, small

#822 7893 Fix ComplianceControlSetCloner
  lib/compliance_control_set_cloner.rb
  spec/lib/compliance_control_set_cloner_spec.rb
Labels: bug, small

#830 7795 Add missing index on routes#line_id
  db/migrate/20180820075337_add_index_on_routes_line_id.rb
Labels: enhancement, small

#833 Refs #7822 Add seasonal attribute to permitted params
  app/controllers/lines_controller.rb
Labels: small

#832 Refs #7857 Fix color display of select 2 results for timetable & deta…
  app/javascript/vehicle_journeys/components/VehicleJourneys.js
  app/javascript/vehicle_journeys/components/tools/select2s/TimetableSelect2.js
Labels: small

#749 7603 Add a lib to get the current app version
  app/assets/stylesheets/components/_main_nav.sass
  app/views/layouts/navigation/_main_nav_left.html.slim
  lib/version.rb
  spec/fixtures/invalid_version.json
  spec/fixtures/valid_version.json
  spec/lib/version_spec.rb
Labels: enhancement

#842 7962 Make CustomFields cache flushable
  app/models/concerns/custom_fields_support.rb
  spec/models/custom_field_spec.rb
Labels: bug, urgent

#845 7974 Fill existing workbenches prefix
  db/migrate/20180824133331_set_existing_workbenches_prefix.rb
Labels: bug, small, urgent

#839 7941 Use routes costs for distances computation
  app/javascript/journey_patterns/components/JourneyPattern.js
Labels: bug, urgent

#846 7982 Add a mechanism to temporarily ignore vulnerabilities
  lib/tasks/ci.rake
Labels: enhancement, small

#850 7894 Fix Calendar show
  app/views/calendars/show.html.slim
Labels: bug, small

#848 7996 Compny filter disappeared
  app/views/referential_vehicle_journeys/_filters.html.slim
Labels: bug, small

#853 #8001 Ensure workbench prefixes are suitable for referentials
  app/models/workbench.rb
  db/migrate/20180828143534_normalize_workbench_prefixes.rb
  spec/models/workbench_spec.rb
Labels: bug, small

#854 8002 Set referentials back to active if pre-merge validations …
  app/models/merge.rb
  spec/models/merge_spec.rb
Labels: bug, small

#857 8007 Add missing indexes
  db/migrate/20180829151132_add_missing_indexes.rb
Labels: enhancement, small

#860 8012 Fix StopArea validation
  app/models/chouette/stop_area.rb
Labels: bug, small

#868 8025 Fix control when vj has no bouding dates
  app/models/vehicle_journey_control/purchase_window_dates.rb
  spec/models/compliance_controls/vehicle_journey_control/purchase_window_dates_spec.rb
Labels: bug, small, urgent

#864 8029 Fix checksums
  app/models/chouette/journey_pattern.rb
  app/models/chouette/route.rb
  app/models/chouette/routing_constraint_zone.rb
Labels: bug, small, urgent

#865 8030 Fix Workgroup#edit
  app/views/workgroups/_form.html.slim
Labels: bug, small, urgent
