Repository af83/chouette-core, pull requests merged in 2018-07, with the labels that each got.

#670 Refs 7459 Workbench#show filter by default on organisation name & sor…
  app/controllers/workbenches_controller.rb
  app/views/dashboards/_dashboard.html.slim
  app/views/stif/dashboards/_dashboard.html.slim
Labels: small

#676 Refs #6558 DRY up chouette types and refacto without Fixnum
  app/models/chouette/access_point_type.rb
  app/models/chouette/connection_link_type.rb
  app/models/chouette/direction.rb
  app/models/chouette/link_orientation_type.rb
  app/models/chouette/source_type.rb
  app/models/chouette/text_and_numerical_type.rb
  app/models/custom_field.rb
  spec/support/data_modifier.rb
Labels: refactoring

#674 7526 fix rcz
  Gemfile.lock
  app/models/chouette/routing_constraint_zone.rb
  app/models/chouette/stop_point.rb
  app/models/concerns/checksum_support.rb
  lib/tasks/referential.rake
  spec/models/chouette/routing_constraint_zone_spec.rb
  spec/models/route_spec.rb
Labels: bug

#613 7266 New UI for Referentials merges
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.sass
  app/assets/stylesheets/components/_merges.sass
  app/assets/stylesheets/flags.sass
  app/controllers/merges_controller.rb
  app/controllers/referentials_controller.rb
  app/javascript/helpers/merge_referentials_selector.coffee
  app/javascript/packs/merges/new.js
  app/models/referential.rb
  app/views/layouts/application.html.slim
  app/views/merges/_form.html.slim
  config/initializers/assets.rb
  config/locales/merges.en.yml
  config/locales/merges.fr.yml
  config/routes.rb
  vendor/assets/javascripts/jquery-ui.min.js
Labels: enhancement

#678 Refs #7489 Fix link to workbench_output in dashboard
  app/views/dashboards/_dashboard.html.slim
  config/locales/dashboard.en.yml
  config/locales/dashboard.fr.yml
Labels: small

#685 Refs #7555 Fix VJ purchase window multiple affectation bug
  app/javascript/vehicle_journeys/reducers/modal.js
Labels: small

#684 Refs #7468 Fix VJ purchase window color
  app/javascript/vehicle_journeys/components/VehicleJourney.js
  app/javascript/vehicle_journeys/components/tools/PurchaseWindowsEditVehicleJourney.js
  app/javascript/vehicle_journeys/components/tools/select2s/TimetableSelect2.js
Labels: small

#675 Refs #6837
  app/helpers/transport_mode_helper.rb
  config/locales/compliance_control_sets.en.yml
  config/locales/compliance_controls.en.yml
  config/locales/enumerize.en.yml
  config/locales/enumerize.fr.yml
Labels: small

#677 Refs #7537 Fix route sorting
  app/controllers/referential_lines_controller.rb
Labels: small

#709 Refs #7271 - Organisation show
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/layouts/navigation/_main_nav_left_content_stif.html.slim
  app/views/organisations/show.html.slim
  config/locales/layouts.en.yml
  config/locales/layouts.fr.yml
  config/locales/organisations.fr.yml
Labels: enhancement

#584 7101 ControlSets edition
  app/controllers/compliance_check_sets_controller.rb
  app/controllers/compliance_control_sets_controller.rb
  app/models/compliance_check_set.rb
  app/models/compliance_control_set.rb
  app/models/import/resource.rb
  app/models/merge.rb
  app/models/user.rb
  app/models/workgroup.rb
  app/policies/compliance_control_policy.rb
  app/policies/compliance_control_set_policy.rb
  app/views/compliance_check_sets/_filters.html.slim
  app/views/compliance_check_sets/index.html.slim
  app/views/compliance_check_sets/show.html.slim
  app/views/compliance_control_sets/_filters.html.slim
  app/views/compliance_control_sets/index.html.slim
  app/views/compliance_control_sets/show.html.slim
  app/views/layouts/navigation/_main_nav_left_content_stif.html.slim
  config/locales/compliance_check_sets.en.yml
  config/locales/compliance_check_sets.fr.yml
  config/locales/compliance_checks.en.yml
  config/locales/compliance_control_sets.fr.yml
  config/locales/compliance_controls.fr.yml
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
  db/migrate/20180717092218_add_context_to_compliance_check_sets.rb
  lib/compliance_control_set_copier.rb
  spec/controllers/compliance_control_sets_controller_spec.rb
  spec/policies/compliance_control_set_policy_spec.rb
  spec/support/pundit/policies.rb
Labels: enhancement

#695 7552 companies form
  app/assets/stylesheets/base/_utilities.sass
  app/helpers/custom_fields_helper.rb
  app/models/custom_field.rb
  app/views/companies/_form.html.slim
  app/views/companies/show.html.slim
  app/views/referential_companies/_form.html.slim
  app/views/referential_companies/edit.html.slim
  app/views/referential_companies/index.html.slim
  app/views/referential_companies/new.html.slim
  app/views/referential_companies/show.html.slim
  app/views/referential_stop_areas/_form.html.slim
  app/views/referential_stop_areas/_genealogical.html.slim
  app/views/referential_stop_areas/_stop_area.html.slim
  app/views/referential_stop_areas/_stop_areas.html.slim
  app/views/referential_stop_areas/access_links.html.slim
  app/views/referential_stop_areas/add_children.html.slim
  app/views/referential_stop_areas/add_routing_lines.html.slim
  app/views/referential_stop_areas/add_routing_stops.html.slim
  app/views/referential_stop_areas/edit.html.slim
  app/views/referential_stop_areas/index.html.slim
  app/views/referential_stop_areas/index.js.slim
  app/views/referential_stop_areas/index.kml.slim
  app/views/referential_stop_areas/new.html.slim
  app/views/referential_stop_areas/select_parent.html.slim
  app/views/referential_stop_areas/show.html.slim
  app/views/referential_stop_areas/show.kml.slim
  config/locales/companies.en.yml
  config/locales/companies.fr.yml
Labels: enhancement

#669 [DO NOT MERGE] Fix core controls
  app/controllers/compliance_controls_controller.rb
  app/models/company_control/name_is_present.rb
  app/models/compliance_control.rb
  app/models/journey_pattern_control/minimum_length.rb
  app/models/route_control/border_count.rb
  app/models/vehicle_journey_control/bus_capacity.rb
  spec/models/compliance_control_spec.rb
  spec/models/compliance_controls/route_controls/border_count_spec.rb
Labels: bug, small

#722 Refs #7646 Fix CCblock translations on CC#show
  app/views/compliance_controls/show.html.slim
Labels: small

#723 Refs #7594 Switch close modal button to white
  app/assets/stylesheets/components/_modals.sass
Labels: small

#730 Refs #7676 Add class_name prop to Calandar has many :time_tables
  app/models/calendar.rb
Labels: bug

#742 7675 Fix Merge#show
  app/views/merges/show.html.slim
Labels: small

#732 7647 Use a flex layout for Workgroup#edit
  app/assets/stylesheets/_misc.sass
  app/assets/stylesheets/application.sass
  app/models/compliance_control_set.rb
  app/views/workgroups/_form.html.slim
  app/views/workgroups/edit.html.slim
  config/locales/compliance_control_sets.fr.yml
Labels: bug

#741 Refs #7681 Fix Calendar sort on organisation name
  app/controllers/calendars_controller.rb
  app/models/calendar.rb
  app/views/calendars/index.html.slim
Labels: bug, small

#700 7007 - use select2 for country / timeZone inputs
  app/inputs/full_time_zone_input.rb
  app/views/stop_areas/_form.html.slim
Labels: enhancement

#736 Refs #7578 Add id & name to timetable comment input to help for cucum…
  app/javascript/time_tables/components/Metas.js
Labels: enhancement, small

#735 Refs #7670 Remove duplicates in main nav left
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/layouts/navigation/_main_nav_left_content_stif.html.slim
Labels: bug, small

#734 7636 Make attachments removable
  app/assets/stylesheets/components/_forms.sass
  app/helpers/application_helper.rb
  app/models/custom_field.rb
Labels: enhancement

#710 7588 - Use cache and transaction in ReflexSynchronization
  lib/stif/reflex_synchronization.rb
Labels: enhancement

#751 #6643 Use #max instead of #last in PurchaseWindows scopes
  app/models/chouette/purchase_window.rb
  spec/models/chouette/purchase_window_spec.rb
Labels: small

#737 6839 6840 translations
  config/locales/compliance_control_sets.en.yml
  config/locales/compliance_controls.en.yml
Labels: bug, small

#783 7742 Fix display of ComplianceChecks with dynamic attributes
  app/models/compliance_check.rb
Labels: small

#788 Refs #7735 Fix locales
  config/locales/referentials.fr.yml
Labels: enhancement, small

#787 Refs #7370 use higher level comparison to prevent random errors
  spec/services/zip_service_spec.rb
Labels: bug, refactoring, small

#763 7708 Do not fail when a ComplianceControlSet is destroyed
  app/models/workbench.rb
  spec/models/merge_spec.rb
Labels: bug

#791 7763 Update the JP#checksum when costs change
  app/models/chouette/journey_pattern.rb
  lib/tasks/referential.rake
  spec/models/chouette/journey_pattern_spec.rb
Labels: bug
