Repository af83/chouette-core, pull requests merged in 2019-06, with the labels that each got.

#1410 #11793 change translations for notification rules
  app/views/notification_rules/show.html.slim
  config/locales/notification_rule.en.yml
Labels: small

#1408 10931; Enhanced StopArea names localization
  Gemfile
  Gemfile.lock
  Guardfile
  app/assets/javascripts/select2.coffee
  app/assets/stylesheets/components/_stop_area_referentials.sass
  app/controllers/stop_area_referentials_controller.rb
  app/controllers/stop_areas_controller.rb
  app/decorators/stop_area_referential_decorator.rb
  app/helpers/stop_areas_helper.rb
  app/models/chouette/stop_area.rb
  app/models/permission.rb
  app/models/stop_area_referential.rb
  app/policies/stop_area_referential_policy.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/stop_area_referentials/_form.html.slim
  app/views/stop_area_referentials/edit.html.slim
  app/views/stop_area_referentials/show.html.slim
  app/views/stop_areas/_form.html.slim
  config/locales/layouts.en.yml
  config/locales/layouts.fr.yml
  config/locales/stop_area_referential_syncs.fr.yml
  config/locales/stop_area_referentials.fr.yml
  config/routes.rb
  db/migrate/20190521143921_update_localization_keys.rb
  db/migrate/20190522065254_add_locales_to_stop_area_referentials.rb
  db/migrate/20190604133016_update_default_locales.rb
  db/schema.rb
Labels: enhancement

#1426 11830; Add locale selector on HP
  app/views/layouts/navigation/_main_nav_top.html.slim
Labels: bug
