Repository af83/chouette-core, pull requests merged in 2019-02, with the labels that each got.

#1194 Refs #10108 Update fa-lg class to fix trimmed icon
  app/assets/stylesheets/base.sass
Labels: small

#1206 Refs #10226 Fix typo and replace harccoded string with I18n
  app/controllers/concerns/iev_interfaces.rb
  app/helpers/newapplication_helper.rb
  app/views/calendars/_date_value_fields.html.slim
  app/views/calendars/_period_fields.html.slim
  app/views/purchase_windows/_date_value_fields.html.slim
  app/views/purchase_windows/_period_fields.html.slim
  app/views/time_tables/_date_fields.html.slim
  app/views/time_tables/_excluded_date_fields.html.slim
  app/views/time_tables/_period_fields.html.slim
  config/locales/actions.fr.yml
Labels: small

#1207 10385 Add download button on Export#show
  app/decorators/export_decorator.rb
  app/helpers/exports_helper.rb
Labels: small, urgent

#1212 Refs #10363 Fix I18n in user's confirm modals
  lib/af83/decorator/link.rb
Labels: small

#1197 9976 Publish offer after a rollback
  app/models/aggregate.rb
  spec/models/aggregate_spec.rb
Labels: bug, small

#1214 Refs #10352 impport filter translation
  app/views/shared/iev_interfaces/_filters.html.slim
Labels: small

#1204 9865 ChecksumManager: ignore changes on destroyed objects
  lib/chouette/checksum_manager/transactional.rb
  spec/lib/chouette/checksum_manager/transactional_spec.rb
Labels: enhancement

#1129 9910 Fix VehicleJourneys collection URL
  app/models/compliance_controls/custom_field_control/presence.rb
Labels: bug, small

#1192 10283 Optimize files purge
  app/models/import/base.rb
Labels: small

#1198 10293 Prevent warnings during aggregation
  app/models/concerns/referential_copy_helpers.rb
Labels: enhancement, small

#1219 10550 Fix bug in Copy/Paste
  app/javascript/vehicle_journeys/components/CopyModal.js
Labels: bug, small, urgent
