Repository af83/chouette-core, pull requests merged in 2019-05, with the labels that each got.

#1151 8432 Enforce Referentials' slugs uniqueness on DB level
  db/migrate/20190118093554_make_referentials_slugs_unique_again.rb
  db/schema.rb
Labels: dontmerge, urgent

#1382 11692 Fix dashboard
  app/views/layouts/navigation/_main_nav_left.html.slim
Labels: bug, small, urgent

#1373 11613 - Display state change event only if current user has referential edition permission
  app/assets/javascripts/referential_state.coffee
  app/views/layouts/application.html.slim
Labels: dontmerge

#1389 11722 Fix JourneyPatterns edition
  app/controllers/concerns/metadata_controller_support.rb
Labels: bug, urgent

#1352 Refs #11191 wording in aggregates#show page
  app/views/aggregates/show.html.slim
  config/locales/aggregates.en.yml
  config/locales/aggregates.fr.yml
Labels: small

#1374 Refs #11060 update user confirmation workflow
  app/controllers/users/confirmations_controller.rb
  app/views/devise/confirmations/new.html.slim
  config/locales/devise.en.yml
  config/locales/devise.fr.yml
  config/routes.rb
Labels: small

#1391 11711 Fix stopareas form
  app/views/stop_areas/_form.html.slim
Labels: bug, small, urgent

#1390 11725 Fix filters on journeys index
  app/views/referential_vehicle_journeys/_display_parameters.html.slim
Labels: bug, small, urgent

#1393 11731; Fix Cleanups
  app/controllers/clean_ups_controller.rb
Labels: bug, small

#1375 11331 handle deactivated lines
  app/assets/stylesheets/components/_forms.sass
  app/controllers/lines_controller.rb
  app/decorators/line_decorator.rb
  app/helpers/icon_helper.rb
  app/helpers/lines_helper.rb
  app/helpers/referentials_helper.rb
  app/javascript/packs/lines/new.js
  app/lib/chouette/netex/line.rb
  app/models/chouette/line.rb
  app/models/compliance_control.rb
  app/models/compliance_controls/line_control/active.rb
  app/models/compliance_controls/line_control/lines_scope.rb
  app/models/compliance_controls/line_control/route.rb
  app/models/permission.rb
  app/policies/line_policy.rb
  app/views/lines/_filters.html.slim
  app/views/lines/_form.html.slim
  app/views/lines/index.html.slim
  app/views/lines/show.html.slim
  app/views/referential_lines/show.html.slim
  app/views/referentials/show.html.slim
  config/initializers/simple_form_bootstrap.rb
  config/locales/compliance_check_messages.en.yml
  config/locales/compliance_check_messages.fr.yml
  config/locales/compliance_controls.en.yml
  config/locales/compliance_controls.fr.yml
  config/locales/enumerize.en.yml
  config/locales/enumerize.fr.yml
  config/locales/lines.en.yml
  config/locales/lines.fr.yml
  config/routes.rb
  db/migrate/20190502080722_add_validity_period_to_lines.rb
  db/schema.rb
  spec/controllers/lines_controller_spec.rb
  spec/features/lines_spec.rb
  spec/models/chouette/line_spec.rb
  spec/models/compliance_controls/line_control/active_spec.rb
Labels: enhancement

#1392 11701 Fix users invitation
  app/controllers/users_controller.rb
Labels: bug, small, urgent

#1397 11757 Fix netex imports
  app/helpers/application_helper.rb
  app/lib/stif/netex_file.rb
  app/services/workbench_import_service.rb
Labels: urgent

#1371 10376 Purge old referentials
  app/lib/cron.rb
  app/lib/smart_env.rb
  app/models/referential.rb
  config/application.rb
  config/environments/development.rb
  config/initializers/cron.rb
  spec/factories/merges.rb
  spec/factories/referentials.rb
  spec/models/referential_spec.rb
Labels: enhancement, urgent

#1400 11773 Fix issue with nightly aggregation time
  app/lib/local_daytime.rb
  app/models/concerns/referential_index_support.rb
  app/models/workgroup.rb
  spec/models/concerns/referential_index_support_spec.rb
  spec/models/workgroup_spec.rb
Labels: urgent

#1409 #11794 link to support center
  app/assets/images/icons/chaticon.svg
  app/views/layouts/navigation/_main_nav_top.html.slim
  app/views/layouts/navigation/_nav_panel_profile.html.slim
  config/locales/layouts.en.yml
  config/locales/layouts.fr.yml
Labels: small

#1417 10863; Update devise gem
  Gemfile.lock
Labels: small, urgent

#1419 11816; Fix exports form
  app/views/exports/_form.html.slim
Labels: bug, small, urgent
