Repository af83/chouette-core, pull requests merged in 2019-04, with the labels that each got.

#1305 Refs #9731 add missing translations
  app/models/aggregates/nightly_aggregate.rb
  app/models/workgroup.rb
  app/views/workgroups/edit_aggregate.html.slim
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
Labels: small

#1304 Refs #11045 Add missing translations
  config/locales/vehicle_journeys.en.yml
Labels: small

#1302 Refs #11038 #11042 Fix Z-index issue
  app/assets/stylesheets/_misc.sass
  app/javascript/journey_patterns/components/CreateModal.js
Labels: bug

#1309 9757 Add default value for PublicationSetup#export_options
  app/models/publication_setup.rb
Labels: bug, small, urgent

#1295 10950 Enable development toolbar with an ENV var
  .dockerignore
  .gitignore
  config/application.rb
  config/development_toolbar.rb
  config/environments/development.rb
  config/environments/production.rb.sample
Labels: enhancement

#1317 Refs #11045 Fix i18n
  config/locales/vehicle_journeys.en.yml
Labels: small

#1293 Refs #10228 Display password hint if user has password set
  app/views/devise/registrations/edit.html.slim
  config/locales/devise.fr.yml
Labels: small

#1318 11122 Fix Exports options
  app/helpers/exports_helper.rb
  app/models/export/option_proxy.rb
Labels: bug, small

#1329 11148 Stronger policies for publications
  app/models/user.rb
  app/policies/publication_api_policy.rb
  app/policies/publication_setup_policy.rb
  app/views/publication_apis/index.html.slim
  app/views/publication_setups/index.html.slim
Labels: bug, urgent

#1327 11149 Keep only one destination by default
  app/models/destination.rb
Labels: bug, urgent

#1316 11144 Fix Nightly Aggregates
  app/models/workgroup.rb
Labels: bug, small, urgent

#1334 11185 Add min/max constraints on export options
  app/models/concerns/options_support.rb
  app/models/export/netex.rb
  app/models/publication_setup.rb
  spec/factories/publication_setups.rb
  spec/models/export/netex_spec.rb
Labels: bug

#1069 Refs #7808 Remove user parameter from i18n user key on show page
  config/locales/users.en.yml
  config/locales/users.fr.yml
Labels: small

#1340 Refs #11222 fix i18n
  config/locales/destinations.en.yml
  config/locales/layouts.en.yml
  config/locales/publication_api_keys.en.yml
  config/locales/publication_api_sources.en.yml
  config/locales/publication_setups.en.yml
Labels: small

#1341 Refs #11146 fix wording
  config/locales/aggregates.fr.yml
  config/locales/workgroup_outputs.fr.yml
Labels: small

#1337 Refs #8988 fix timetable confirm modal i18n
  config/locales/time_tables.fr.yml
Labels: small

#1301 Refs #11031 Fix I18n for select2
  app/javascript/helpers/CustomFieldsInputs.js
  app/javascript/helpers/select2/language.js
  app/javascript/routes/components/BSelect2.js
  app/javascript/vehicle_journeys/components/tools/select2s/CompanySelect2.js
  app/javascript/vehicle_journeys/components/tools/select2s/ConstraintZoneSelect2.js
  app/javascript/vehicle_journeys/components/tools/select2s/MissionSelect2.js
  app/javascript/vehicle_journeys/components/tools/select2s/TimetableSelect2.js
  app/javascript/vehicle_journeys/components/tools/select2s/VJSelect2.js
Labels: bug, small

#1307 Refs #10748 beginning of clean up refacto
  app/assets/javascripts/cleanup.coffee
  app/assets/stylesheets/_misc.sass
  app/controllers/clean_ups_controller.rb
  app/decorators/referential_decorator.rb
  app/models/application_model.rb
  app/models/chouette/journey_pattern.rb
  app/models/chouette/route.rb
  app/models/chouette/time_table.rb
  app/models/chouette/time_tables_vehicle_journey.rb
  app/models/chouette/vehicle_journey.rb
  app/models/clean_up.rb
  app/models/concerns/clean_up_methods.rb
  app/models/concerns/options_support.rb
  app/models/merge.rb
  app/models/referential.rb
  app/views/clean_ups/new.html.slim
  app/views/referentials/show.html.slim
  config/locales/actions.fr.yml
  config/locales/clean_ups.en.yml
  config/locales/clean_ups.fr.yml
  config/locales/enumerize.fr.yml
  config/routes.rb
  db/migrate/20190416143445_add_method_types_to_cleanups.rb
  db/schema.rb
  spec/decorators/referential_decorator_spec.rb
  spec/factories/chouette_time_table.rb
  spec/models/chouette/time_table_spec.rb
  spec/models/clean_up_spec.rb
Labels: dontmerge, enhancement, refactoring

#1349 Refs #11192 Fix wrong number in select toolbox
  app/assets/javascripts/selectable_table.coffee
Labels: small

#1347 Refs #10770 refacto headers display
  app/assets/stylesheets/components/_page_header.sass
  app/helpers/application_helper.rb
  app/views/journey_patterns_collections/show.html.slim
  app/views/layouts/navigation/_page_header.html.slim
  app/views/vehicle_journeys/index.html.slim
  config/locales/calendars.en.yml
  config/locales/calendars.fr.yml
  config/locales/companies.en.yml
  config/locales/companies.fr.yml
  config/locales/compliance_control_sets.en.yml
  config/locales/compliance_control_sets.fr.yml
  config/locales/compliance_controls.en.yml
  config/locales/compliance_controls.fr.yml
  config/locales/exports.en.yml
  config/locales/exports.fr.yml
  config/locales/imports.en.yml
  config/locales/imports.fr.yml
  config/locales/journey_patterns.en.yml
  config/locales/journey_patterns.fr.yml
  config/locales/lines.en.yml
  config/locales/lines.fr.yml
  config/locales/networks.en.yml
  config/locales/networks.fr.yml
  config/locales/publication_api_keys.fr.yml
  config/locales/publication_apis.en.yml
  config/locales/publication_apis.fr.yml
  config/locales/publication_setups.en.yml
  config/locales/publication_setups.fr.yml
  config/locales/publications.en.yml
  config/locales/publications.fr.yml
  config/locales/purchase_windows.en.yml
  config/locales/purchase_windows.fr.yml
  config/locales/referentials.en.yml
  config/locales/referentials.fr.yml
  config/locales/routes.en.yml
  config/locales/routes.fr.yml
  config/locales/routing_constraint_zones.en.yml
  config/locales/routing_constraint_zones.fr.yml
  config/locales/stop_area_providers.en.yml
  config/locales/stop_area_providers.fr.yml
  config/locales/stop_area_routing_constraints.en.yml
  config/locales/stop_area_routing_constraints.fr.yml
  config/locales/stop_areas.en.yml
  config/locales/stop_areas.fr.yml
  config/locales/time_tables.en.yml
  config/locales/time_tables.fr.yml
Labels: small

#1359 Refs #11421 add contain urgent offer in referential duplication form
  app/models/referential.rb
  app/views/referentials/_form.html.slim
Labels: small

#1239 9532 route form
  .babelrc
  app/assets/javascripts/forms.coffee
  app/assets/javascripts/routes.coffee
  app/assets/stylesheets/components/_main_nav.sass
  app/controllers/routes_controller.rb
  app/javascript/packs/routes/edit.js
  app/javascript/packs/routes/form.js
  app/javascript/routes/actions/index.js
  app/javascript/routes/components/App.js
  app/javascript/routes/components/BSelect2.js
  app/javascript/routes/components/CancelRoute.js
  app/javascript/routes/components/SaveRoute.js
  app/javascript/routes/components/StopPoint.js
  app/javascript/routes/components/StopPointList.js
  app/javascript/routes/components/form/SelectInput.js
  app/javascript/routes/components/form/SwitchInput.js
  app/javascript/routes/components/form/TextInput.js
  app/javascript/routes/components/form/index.js
  app/javascript/routes/containers/App.js
  app/javascript/routes/containers/CancelRoute.js
  app/javascript/routes/containers/Route.js
  app/javascript/routes/containers/SaveRoute.js
  app/javascript/routes/containers/VisibleStopPoints.js
  app/javascript/routes/form_helper.js
  app/javascript/routes/index.js
  app/javascript/routes/reducers/deletedStopPoints.js
  app/javascript/routes/reducers/formErrors.js
  app/javascript/routes/reducers/index.js
  app/javascript/routes/reducers/oppositeRoutes.js
  app/javascript/routes/reducers/route.js
  app/javascript/routes/reducers/status.js
  app/javascript/routes/reducers/stopPoints.js
  app/models/chouette/route.rb
  app/models/chouette/stop_point.rb
  app/views/routes/_form.html.slim
  app/views/routes/edit.html.slim
  app/views/routes/new.html.slim
  app/views/routes/show.rabl
  app/views/routes/stop_points/show.rabl
  config/locales/flash_responders.en.yml
  config/locales/flash_responders.fr.yml
  config/locales/routes.en.yml
  config/locales/routes.fr.yml
  config/routes.rb
  package.json
  spec/javascript/routes/actions_spec.js
  spec/javascript/routes/helpers/index.js
  spec/javascript/routes/reducers/deletedStopPoints_spec.js
  spec/javascript/routes/reducers/formErrors_spec.js
  spec/javascript/routes/reducers/oppositeRoutes_spec.js
  spec/javascript/routes/reducers/route_spec.js
  spec/javascript/routes/reducers/status_spec.js
  spec/javascript/routes/reducers/stop_points_spec.js
  yarn-error.log
  yarn.lock
Labels: refactoring
