Repository af83/chouette-core, pull requests merged in 2019-07, with the labels that each got.

#1450 12008; Fix StopAreaReferential
  app/models/stop_area_referential.rb
Labels: bug, small, urgent

#1451 12006; Fix GTFS import
  app/models/import/gtfs.rb
Labels: bug

#1396 11741; Fix routes cleaning
  app/models/chouette/route.rb
Labels: bug, urgent

#1343 11181 fix opposite routes merge and aggregate
  app/models/chouette/route.rb
  app/models/merge.rb
  app/models/referential.rb
  spec/models/route_spec.rb
  spec/services/referential_copy_spec.rb
Labels: bug

#1455 12051; Fix Footnotes deletion
  app/models/chouette/line.rb
  spec/controllers/footnotes_controller_spec.rb
Labels: bug

#1303 Refs #11044 Add english translations for copy paste vj modal
  config/locales/courses_copy_paste.en.yml
Labels: small

#1460 Refs #11460 fix english transation for publications
  config/locales/publications.en.yml
Labels: small

#1461 Refs #11709 display export status on show page
  app/helpers/exports_helper.rb
Labels: small

#1466 12063; Fix times assignments in VJAS
  app/models/chouette/vehicle_journey_at_stop.rb
  spec/models/chouette/vehicle_journey_at_stop_spec.rb
Labels: bug, urgent

#1464 Refs #11833 i18n for stop areas
  config/locales/enumerize.en.yml
  config/locales/enumerize.fr.yml
  config/locales/stop_areas.en.yml
Labels: small

#1463 #11737 add a default color for Chouette::Line
  app/controllers/lines_controller.rb
Labels: small

#1462 #11577 Update imports' calendars name
  app/models/import/gtfs.rb
  spec/models/import/gtfs_spec.rb
Labels: small

#1471 #1165 fix line text color display in referential overview
  app/services/referential_overview.rb
  app/views/referentials/_overview.html.slim
Labels: small

#1472 11182 publication setup
  app/views/publication_setups/index.html.slim
Labels: small
