Repository af83/chouette-core, pull requests merged in 2019-03, with the labels that each got.

#1240 Refs #10661 Change Oid by Id
  app/views/companies/index.html.slim
  app/views/networks/index.html.slim
  app/views/referential_lines/show.html.slim
  config/locales/vehicle_journeys.fr.yml
Labels: small

#1174 Refs #10095 Add changes to transport mode & submode behaviours
  app/assets/stylesheets/components/_forms.sass
  app/controllers/concerns/transport_mode_filter.rb
  app/controllers/lines_controller.rb
  app/helpers/lines_helper.rb
  app/javascript/packs/lines/index.js
  app/views/lines/_filters.html.slim
  app/views/lines/index.html.slim
Labels: enhancement

#1181 Improve Audit Mail
  app/mailers/audit_mailer.rb
  app/services/referential_audit/full.rb
  app/services/referential_audit/full_referential.rb
  app/services/referential_audit/vehicle_journey_initial_offset.rb
  config/locales/mailers.fr.yml
Labels: enhancement, small

#1246 10654 In VJs editor, remove calendars button
  app/javascript/vehicle_journeys/components/Tools.js
  app/javascript/vehicle_journeys/components/tools/CopyButton.js
  app/javascript/vehicle_journeys/components/tools/PasteButton.js
  app/javascript/vehicle_journeys/components/tools/SelectVehicleJourneys.js
  config/locales/actions.en.yml
  config/locales/actions.fr.yml
Labels: small

#1245 10696 Fix exports form
  app/controllers/exports_controller.rb
Labels: bug, small

#1250 Refs #10699 Add confirm modal for Aggregate#rollback
  app/decorators/aggregate_decorator.rb
  config/locales/aggregates.en.yml
  config/locales/aggregates.fr.yml
Labels: small

#1248 10492 Add audit on JourneyPatterns
  app/services/referential_audit/base.rb
  app/services/referential_audit/journey_pattern_stop_points.rb
  app/services/referential_audit/vehicle_journey_at_stop_times.rb
Labels: enhancement, small

#1118 8236 Remove subproject code
  lib/stif/codif_line_synchronization.rb
  lib/stif/codifligne_line_id.rb
  lib/stif/dashboard.rb
  lib/stif/reflex_synchronization.rb
  lib/stif/workbench_scopes.rb
  spec/lib/stif/netex_file/frame_spec.rb
Labels: enhancement, refactoring

#1253 Refs #10711 Refs #10494 Fix I18n & breadcrumb
  config/breadcrumbs.rb
Labels: small

#1247 10646 make transport mode mandatory
  app/controllers/lines_controller.rb
  app/views/lines/_form.html.slim
Labels: small

#1164 10140 Grant permission to workgroups owners
  app/controllers/compliance_check_sets_controller.rb
  app/helpers/application_helper.rb
  app/helpers/compliance_check_sets_helper.rb
  app/helpers/imports_helper.rb
  app/policies/compliance_check_set_policy.rb
  app/policies/workbench_policy.rb
  spec/policies/compliance_check_set_policy_spec.rb
Labels: urgent

#1244 10697 Set a default duration for NETEX line exports
  app/helpers/exports_helper.rb
  app/models/concerns/options_support.rb
  app/models/export/netex.rb
Labels: bug, small

#1226 10580 In the seeds, don't create a workgroup if the organization already has one
  db/seeds/helpers/workgroups.rb
Labels: urgent

#1251 Refs #10623 Fix translation in main nav left menu
  config/locales/compliance_check_sets.en.yml
  config/locales/compliance_control_sets.en.yml
Labels: small

#1262 10778 Fix bug in aggregation
  app/models/workgroup.rb
Labels: bug, urgent

#1267 10784 fix audits
  app/mailers/audit_mailer.rb
  app/services/referential_audit/checksums.rb
Labels: bug, small, urgent

#1263 10781 Update vehilce journeys checksums
  app/models/stop_area_routing_constraint.rb
  spec/models/chouette/vehicle_journey_spec.rb
  spec/models/stop_area_routing_constraint_spec.rb
Labels: bug, urgent

#1269 10822 Fix WorkgroupOutputsController#show
  app/policies/nightly_aggregate_policy.rb
Labels: bug, small, urgent

#1270 10809 Fix offset calculation
  app/models/chouette/vehicle_journey.rb
  app/models/chouette/vehicle_journey_at_stops_day_offset.rb
  spec/models/chouette/vehicle_journey_at_stops_day_offset_spec.rb
Labels: bug, urgent

#1272 10740 Fail pending referentials
  app/models/import/base.rb
  config/initializers/delayed_job.rb
Labels: small

#1276 10848 Fix missing i18n in StopAreaRoutingConstraint#show
  app/views/stop_area_routing_constraints/index.html.slim
  app/views/stop_area_routing_constraints/show.html.slim
Labels: bug, small

#1243 10649 Fix potential bug in merge
  app/models/merge.rb
Labels: bug, small

#1286 10918 Fix errors controller for unauthenticated users
  app/controllers/errors_controller.rb
Labels: bug, small

#1280 Refs #10456 redirect after submit (calendars & timetables)
  app/javascript/time_tables/actions/index.js
  app/views/calendars/_form_advanced.html.slim
  app/views/calendars/edit.html.slim
  app/views/time_tables/edit.html.slim
Labels: small

#1277 Refs #10798 Remove workgroups header buttons
  app/decorators/workgroup_decorator.rb
Labels: small

#1150 8207 Update apartment gem
  Gemfile
  Gemfile.lock
Labels: enhancement

#1173 9933 ccset action links z index
  app/assets/stylesheets/_misc.sass
  app/assets/stylesheets/components/_dropdown.sass
Labels: bug

#1218 9082 Add NotificationRule
  app/controllers/notification_rules_controller.rb
  app/controllers/workbenches_controller.rb
  app/decorators/notification_rule_decorator.rb
  app/helpers/notification_rules_helper.rb
  app/models/chouette/line.rb
  app/models/notification_rule.rb
  app/models/permission.rb
  app/models/workbench.rb
  app/policies/notification_rule_policy.rb
  app/services/hole_sentinel.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/notification_rules/_filters.html.slim
  app/views/notification_rules/_form.html.slim
  app/views/notification_rules/edit.html.slim
  app/views/notification_rules/index.html.slim
  app/views/notification_rules/new.html.slim
  app/views/notification_rules/show.html.slim
  config/breadcrumbs.rb
  config/initializers/ransack.rb
  config/locales/layouts.fr.yml
  config/locales/notification_rule.en.yml
  config/locales/notification_rules.fr.yml
  config/routes.rb
  db/migrate/20190210225806_create_notification_rules.rb
  db/schema.rb
  spec/factories/notification_rules.rb
  spec/models/notification_rule_spec.rb
  spec/models/workbench_spec.rb
  spec/policies/notification_rule_policy_spec.rb
  spec/services/holes_sentinel_spec.rb
Labels: urgent

#1294 Refs #9640 Fix CSS for imports file input in errored state
  app/views/imports/_form.html.slim
Labels: small

#1297 10968 Do not retry failed jobs
  app/jobs/long_running_job.rb
Labels: bug, small

#1076 9657 Remove useless audit
  app/services/referential_audit/purchase_windows_checksums.rb
Labels: small

#1299 10271 Update Neptune imports
  app/models/import/neptune.rb
  spec/fixtures/sample_neptune_large.zip
  spec/models/import/neptune_spec.rb
Labels: bug
