Repository af83/chouette-core, pull requests merged in 2019-01, with the labels that each got.

#1101 7554 breadcrumbs
  config/breadcrumbs.rb
Labels: enhancement, small

#1100 Refs #9723 Change mail-notifications-select options wording
  config/locales/operation_support.en.yml
  config/locales/operation_support.fr.yml
Labels: enhancement, small

#1095 Refs #9733 Exclude Referentials that have been created after the curr…
  app/models/referential.rb
  app/models/referential_suite.rb
  app/views/workgroups/edit_aggregate.html.slim
  spec/models/referential_suite/referential_suite_spec.rb
Labels: bug, small

#1055 Refs #9540 Rename workgroups#edit route
  app/controllers/workgroups_controller.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/workgroups/edit_controls.html.slim
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
  config/routes.rb
  spec/views/layouts/menu.html.erb_spec.rb
Labels: small

#1106 9660 invitation mailer
  app/mailers/devise_mailer.rb
  app/views/devise/mailer/invitation_instructions.html.slim
Labels: bug, small

#1111 9278 Add AUTOMATED_AUDITS_ENABLED
  script/launch-cron
Labels: small

#1112 9867 Fix Imports#new
  app/inputs/switchable_checkbox_input.rb
Labels: bug, small, urgent

#1114 9870 Fix Merge icon color for disabled status
  app/assets/stylesheets/typography/_typography.sass
  app/helpers/merges_helper.rb
  app/helpers/operations_helper.rb
Labels: small

#1117 9885 Fix Destination#local_secret_file
  app/models/destination.rb
Labels: bug, small, urgent

#1113 9864 Disable checksums transactions via an ENV var
  config/application.rb
  config/environments/test.rb
  lib/chouette/checksum_manager.rb
Labels: enhancement, small

#1119 9886 Protect VJs list
  app/views/referential_vehicle_journeys/_list.html.slim
Labels: bug, small

#1120 9888 Homogenize periods behaviour
  app/models/calendar.rb
  app/models/chouette/time_table.rb
Labels: bug, small

#1091 Refs #9732 #9729 Demandeur -> Opérateur
  config/locales/aggregates.fr.yml
  config/locales/merges.fr.yml
Labels: enhancement, small

#1123 9892 Ignore empty exports
  app/models/destination/google_cloud_storage.rb
Labels: bug, small, urgent

#1125 9894 Fix destinations
  app/models/destination.rb
  app/models/destination/google_cloud_storage.rb
  app/models/destination/sftp.rb
Labels: bug

#1124 9893 Fix default SFTP port
  app/models/concerns/options_support.rb
Labels: bug, small

#1126 9896 Hide secret keys
  app/helpers/publications_helper.rb
Labels: bug, small

#1128 9892 Fix publications with empty exports
  app/models/destination/google_cloud_storage.rb
Labels: bug, small, urgent

#1133 9930 custom field control show
  app/helpers/compliance_controls_helper.rb
Labels: bug

#1132 Refs #9928 Fix typo that generates import error
  app/models/import/gtfs.rb
Labels: bug

#1131 Refs #9936 Fix Compliance Control Block form
  app/controllers/compliance_control_blocks_controller.rb
  app/helpers/compliance_control_blocks_helper.rb
  app/views/compliance_control_blocks/_form.html.slim
Labels: bug

#1109 Refs #9852 Add aggregated_at column in WorkbenchOutput#show
  app/decorators/merge_decorator.rb
  app/models/merge.rb
  app/views/workbench_outputs/show.html.slim
  config/locales/workbench_outputs.en.yml
  config/locales/workbench_outputs.fr.yml
  spec/decorators/merge_decorator_spec.rb
Labels: enhancement, small

#1070 Refs #9542 Rollback workbench route naming to normal behaviour
  app/controllers/workbenches_controller.rb
  app/views/layouts/navigation/_main_nav_left_content.html.slim
  app/views/workbenches/_form.html.slim
  app/views/workbenches/edit.html.slim
  app/views/workbenches/show.html.slim
  config/breadcrumbs.rb
  config/locales/workbenches.en.yml
  config/locales/workbenches.fr.yml
  config/routes.rb
  spec/views/layouts/menu.html.erb_spec.rb
Labels: small

#1089 Refs #9505 Display notification targets in orerations table builder
  app/helpers/aggregates_helper.rb
  app/helpers/compliance_check_sets_helper.rb
  app/helpers/exports_helper.rb
  app/helpers/imports_helper.rb
  app/helpers/merges_helper.rb
  app/helpers/stop_areas_helper.rb
  app/views/aggregates/show.html.slim
  app/views/compliance_check_sets/index.html.slim
  app/views/compliance_check_sets/show.html.slim
  app/views/exports/show.html.slim
  app/views/imports/import/_gtf.html.slim
  app/views/imports/import/_netex.html.slim
  app/views/imports/import/_workbench.html.slim
  app/views/merges/show.html.slim
  app/views/stop_areas/show.html.slim
  config/breadcrumbs.rb
Labels: enhancement, small

#1135 Refs #9929 Enable other organisation from same workgroup to access im…
  app/controllers/imports_controller.rb
  app/policies/import_policy.rb
  app/views/imports/index.html.slim
  spec/policies/import_policy_spec.rb
Labels: bug

#1141 9987 Fix ComplianceControl specs
  spec/models/compliance_controls/journey_pattern_controls/min_max_distance_cost_spec.rb
  spec/models/compliance_controls/journey_pattern_controls/minimum_length_spec.rb
  spec/models/compliance_controls/route_controls/border_count_spec.rb
  spec/models/compliance_controls/route_controls/stop_points_boarding_and_alighting_spec.rb
  spec/models/compliance_controls/route_controls/valid_stop_areas_spec.rb
Labels: small, urgent

#1149 Refs #10050 Fix PG::UndefinedTable error on referentials lines filter
  app/models/referential.rb
Labels: bug, small

#1143 Refs #9543 A non commercial stop area cannot have a parent
  app/models/chouette/stop_area.rb
  config/locales/stop_areas.en.yml
  config/locales/stop_areas.fr.yml
  spec/models/chouette/stop_area_spec.rb
Labels: small

#1148 10051 min max distance cost control criticity
  app/models/compliance_controls/journey_pattern_control/min_max_distance_cost.rb
Labels: urgent

#1156 Refs #10068 Change Referential create success message
  app/controllers/referentials_controller.rb
  config/locales/referentials.en.yml
  config/locales/referentials.fr.yml
Labels: enhancement, small

#1154 Refs #10092 Remove required attribute for lines#transport_mode input
  app/views/lines/_form.html.slim
Labels: small

#1157 Refs #9947 Fix link TT link to associated calendar
  app/controllers/time_tables_controller.rb
  app/views/time_tables/show.html.slim
Labels: bug

#1169 Refs #9163 Fix I18n typo
  config/locales/layouts.en.yml
Labels: small

#1162 Refs #9955 Add scrollable behaviour for main nav left component
  app/assets/stylesheets/components/_main_nav.sass
Labels: small

#1160 Refs #10048 Add english translations for publication setups
  config/locales/publication_setups.en.yml
Labels: small

#1155 10079 Fix Aggregation
  app/models/concerns/period_support.rb
  app/models/concerns/referential_copy_helpers.rb
  app/services/referential_copy.rb
  db/schema.rb
Labels: bug

#1177 10126 Accept different namespaces in Netex files parsing
  lib/stif/netex_file.rb
  spec/fixtures/netex_file_different_namespace.zip
  spec/fixtures/netex_file_no_namespace.zip
  spec/lib/stif/netex_file_spec.rb
Labels: bug

#1127 Refs #9868 rename workgroups#edit title
  config/locales/workgroups.en.yml
  config/locales/workgroups.fr.yml
Labels: small

#1153 10054 Fix CleanUp worker
  app/models/clean_up.rb
Labels: bug, small

#1122 9556 Secure publications access
  app/controllers/publication_api_keys_controller.rb
  app/controllers/publication_apis_controller.rb
  app/controllers/publication_setups_controller.rb
  app/controllers/publications_controller.rb
Labels: urgent

#1178 Users Management UI
  app/controllers/users/passwords_controller.rb
  app/controllers/users_controller.rb
  app/policies/user_policy.rb
  config/locales/users.en.yml
  config/locales/users.fr.yml
  config/routes.rb
  spec/controllers/users_controller_spec.rb
  spec/support/devise.rb
Labels: urgent

#1163 Refs #10144 remove link from workgroups imports table builder
  app/controllers/concerns/iev_interfaces.rb
  app/policies/workbench_policy.rb
Labels: bug, small, urgent

#1180 9897 Fix PublicationSetup form JS
  app/javascript/publication_setups/new.coffee
Labels: urgent

#1189 10262 Prevent error during import creation
  app/models/concerns/import_resources_support.rb
Labels: bug, small
